env:
  global:

language: c++
dist: bionic
before_install:
  - sudo apt-get update
  - sudo apt-get install -y gcovr lcov cmake gcc-avr binutils-avr avr-libc arduino-core python3-pip

jobs:
  include:
    - stage: "AVR target"
      name: "AVR target"
      compiler: avr-gcc
      script:
        - pip3 install setuptools wheel
        - pip3 install platformio
        - pio run
      after_success:
        - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/cache
